IFMApps/Entities/Leave.cs
using System;
using System.Collections.Generic;

namespace IFMApps.Entities;

public partial class Leave
{
    public int Idleave { get; set; }

    public int? Idsite { get; set; }

    public string Pers { get; set; }

    public string Type { get; set; }

    public DateOnly? Sdate { get; set; }

    public DateOnly? Edate { get; set; }

    public string Shift { get; set; }

    public string Cover { get; set; }

    public string Status { get; set; }

    public DateOnly? Updated { get; set; }
}

IFMApps/Entities/Patrol.cs
using System;
using System.Collections.Generic;

namespace IFMApps.Entities;

public partial class Patrol
{
    public int Idpatrol { get; set; }

    public DateOnly? Date { get; set; }

    public int? Idpoint { get; set; }

    public string Pers { get; set; }

    public TimeOnly? Time { get; set; }

    public TimeOnly? Scan { get; set; }
}

IFMApps/Entities/Per.cs
using System;
using System.Collections.Generic;

namespace IFMApps.Entities;

public partial class Per
{
    public int Idpers { get; set; }

    public string Pers { get; set; }

    public string Name { get; set; }

    public string Telephone { get; set; }

    public string Password { get; set; }

    public string Grade { get; set; }

    public int Idsite { get; set; }

    public string Shift { get; set; }

    public int Idroute { get; set; }

    public string Bankacct { get; set; }

    public string Bank { get; set; }

    public string Nric { get; set; }

    public DateOnly? Dob { get; set; }

    public string Status { get; set; }

    public DateOnly? Date { get; set; }
}

IFMApps/Controllers/PersController.cs
using IFMApps.Dtos;
using IFMApps.Entities;
using IFMApps.Extensions;
using IFMApps.Helpers;
using IFMApps.Interface;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;
using System.Text.Json.Nodes;

namespace IFMApps.Controllers
{
    [Authorize]
    public class PersController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly IAuthServices _authService;
        private readonly IConfiguration _configuration;

        public PersController(IUnitOfWork uow, IAuthServices authService, IConfiguration configuration)
        {
            _configuration = configuration;
            _uow = uow;
            _authService = authService;
        }
        public async Task<IActionResult> Index()
        {
            JsonArray jsonArray = new()
                {
                    User.FindFirst(ClaimTypes.NameIdentifier)?.Value
                };
            var ViewGuard = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.ViewPers, jsonArray);
            var ViewGuardModel = ViewGuard.ToDataSetDto();

            if (TempData["Function"] != null)
            {
                ViewBag.Function = TempData["Function"].ToString();
            }

            return View(ViewGuardModel);
        }

        public async Task<IActionResult> PersAvail()
        {
            JsonArray jsonArray = new()
                {
                    User.FindFirst(ClaimTypes.NameIdentifier)?.Value
                };
            var ViewPers = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.PersAvail, jsonArray);
            var ViewPersModel = ViewPers.ToDataSetDto();

            if (TempData["Function"] != null)
            {
                ViewBag.Function = TempData["Function"].ToString();
            }

            return View(ViewPersModel);

        }

        public async Task<IActionResult> TakeAttend(int idAttend)
        {
            JsonArray jsonArray = new()
                {
                    idAttend,
                    User.FindFirst(ClaimTypes.NameIdentifier)?.Value
                };
            var TakeAttend = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.TakeAttend, jsonArray);
            var TakeAttendModel = TakeAttend.ToSubmitResponseDto<BaseResponseDto>();

            TempData["Function"] = string.Format("SwalAlert('{0}', '{1}', '{2}');", TakeAttendModel.Msg, TakeAttendModel.Msg2, "info");

            return RedirectToAction(nameof(PersAvail));
        }

        public IActionResult Leave()
        {
            ViewBag.LeaveType = _uow.DropdownRepository.GetDrpFieldValue("leave_type", "");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Leave(LeaveSubmissionParam leaveSubmissionParams)
        {
            ViewBag.LeaveType = _uow.DropdownRepository.GetDrpFieldValue("leave_type", "");

            if (ModelState.IsValid)
            {
                leaveSubmissionParams.Pers = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                var jsonArrayParam = leaveSubmissionParams.ConvertToJsonArray<LeaveSubmissionParam>();
                var LeaveResponse = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.UpdateLeave, jsonArrayParam); ;
                var LeaveResponseModel = LeaveResponse.ToSubmitResponseDto<LeaveSubmissionResponse>();

                if (LeaveResponseModel.Msg == "OK")
                    ViewBag.Function = string.Format("SwalAlert('{0}', '{1}', '{2}');", "Submit Leave success", LeaveResponseModel.Msg2, "success");
                else
                    ViewBag.Function = string.Format("SwalAlert('{0}', '{1}', '{2}');", "Submit Leave fail", LeaveResponseModel.Msg2, "error");

            }


            return View();
        }

        [HttpPost]
        public async Task<JsonResult> ClockIn(ClockInOutParam clockInOutParams)
        {
            clockInOutParams.Pers = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var jsonArrayParam = clockInOutParams.ConvertToJsonArray<ClockInOutParam>();
            var ClockInResponse = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.ClockIn, jsonArrayParam);
            var ClockInResponseModel = ClockInResponse.ToSubmitResponseDto<ClockInOutResponse>();

            var updatedClaimsIdentity = _authService.AddSiteToClaims(User, clockInOutParams.QROrNFC);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(updatedClaimsIdentity));

            return Json(ClockInResponseModel);
        }

        [HttpPost]
        public async Task<JsonResult> ClockOut(ClockInOutParam clockInOutParams)
        {
            clockInOutParams.Pers = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var jsonArrayParam = clockInOutParams.ConvertToJsonArray<ClockInOutParam>();
            var ClockInResponse = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.ClockOut, jsonArrayParam);
            var ClockInResponseModel = ClockInResponse.ToSubmitResponseDto<ClockInOutResponse>();
            return Json(ClockInResponseModel);
        }

        public async Task<IActionResult> Patrol()
        {
            var PatrolParams = new ViewPatrolParam()
            {
                Date = DateTime.UtcNow.ToSingaporeTimezone().ToString("yyyy-MM-dd"),
                Pers = User.FindFirst(ClaimTypes.NameIdentifier)?.Value
            };
            //var PatrolParams = new ViewPatrolParam()
            //{
            //    Date = "2023-05-22",
            //    Pers = "6004"
            //};
            var jsonArrayParam = PatrolParams.ConvertToJsonArray<ViewPatrolParam>();
            var PatrolResponse = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.NextPoint, jsonArrayParam);
            var PatrolResponseModel = PatrolResponse.ToDataSetDto();

            if (TempData["Function"] != null)
            {
                ViewBag.Function = TempData["Function"].ToString();
            }

            return View(PatrolResponseModel);
        }

        [HttpPost]
        public async Task<JsonResult> ScanPatrol(ScanPatrolParam scanPatrolParams)
        {
            var SiteClockIn = await _uow.UserRepository.GetClockInSiteToday(User);
            if (string.IsNullOrEmpty(SiteClockIn))
            {
                BaseResponseDto baseResponseDto = new BaseResponseDto()
                {
                    Msg = "Scan Patrol Denied",
                    Msg2 = "Please do clockin first !"
                };

                return Json(baseResponseDto);
            }

            scanPatrolParams.Pers = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var jsonArrayParam = scanPatrolParams.ConvertToJsonArray<ScanPatrolParam>();
            var scanPatrolResponse = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.ScanPatrol, jsonArrayParam);
            var scanPatrolResponseModel = scanPatrolResponse.ToModelDto<ScanPatrolResponseDto>();
            if (scanPatrolResponseModel.DT2 != null)
            {
                return Json(scanPatrolResponseModel.DT2.FirstOrDefault());
            }
            else
            {
                return Json(scanPatrolResponseModel.DT1.FirstOrDefault());
            }
        }


        [HttpPost]
        public async Task<JsonResult> ScanPatrol2(ScanPatrolParam scanPatrolParams)
        {
            var SiteClockIn = await _uow.UserRepository.GetClockInSiteToday(User);
            if (string.IsNullOrEmpty(SiteClockIn))
            {
                BaseResponseDto baseResponseDto = new BaseResponseDto()
                {
                    Msg = "Scan Patrol Denied",
                    Msg2 = "Please do clockin first !"
                };

                return Json(baseResponseDto);
            }

            scanPatrolParams.Pers = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var jsonArrayParam = scanPatrolParams.ConvertToJsonArray<ScanPatrolParam>();
            var scanPatrolResponse = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.ScanPatrol2, jsonArrayParam);
            var scanPatrolResponseModel = scanPatrolResponse.ToModelDto<ScanPatrolResponseDto>();
            if (scanPatrolResponseModel.DT2 != null)
            {
                return Json(scanPatrolResponseModel.DT2.FirstOrDefault());
            }
            else
            {
                return Json(scanPatrolResponseModel.DT1.FirstOrDefault());
            }
        }

        [HttpPost]
        public async Task<JsonResult> ScanPatrol3(ScanPatrol3Param scanPatrolParams)
        {
            var SiteClockIn = await _uow.UserRepository.GetClockInSiteToday(User);
            if (string.IsNullOrEmpty(SiteClockIn))
            {
                BaseResponseDto baseResponseDto = new BaseResponseDto()
                {
                    Msg = "Scan Patrol Denied",
                    Msg2 = "Please do clockin first !"
                };

                return Json(baseResponseDto);
            }

            var jsonArrayParam = scanPatrolParams.ConvertToJsonArray<ScanPatrol3Param>();
            var scanPatrolResponse = await _uow.CommonRepository.GuardWebRequest(IFMAPIUrl.ScanPatrol3, jsonArrayParam);
            var scanPatrolResponseModel = scanPatrolResponse.ToModelDto<ScanPatrolResponseDto>();
            if (scanPatrolResponseModel.DT2 != null)
            {
                return Json(scanPatrolResponseModel.DT2.FirstOrDefault());
            }
            else
            {
                return Json(scanPatrolResponseModel.DT1.FirstOrDefault());
            }
        }

        [HttpPost]
        public async Task<JsonResult> ScanPatrolQR(ScanPatrolParam scanPatrolParams)
        {
            var SiteClockIn = await _uow.UserRepository.GetClockInSiteToday(User);

IFMApps/Views/Pers/Leave.cshtml
@model IFMApps.Helpers.LeaveSubmissionParam
@{
    ViewData["Title"] = "Leave Page";

}
<div class="container removemargincontainer">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 widthdesktop">
            <div class="card">
                <div class="card-header">
                    <h4>Apply For Leave</h4>
                </div>
                <div class="card-body removemargin">
                    @using (Html.BeginForm("Leave", "Pers", FormMethod.Post))
                    {
                        <div class="form-group">
                            <label for="username">Leave Type:</label>
                            @Html.DropDownListFor(o=>o.LeaveType,ViewBag.Site as List<SelectListItem>, new { @class="form-control" , @style = "width:100%"})
                        </div>
                        <div class="form-group">
                            <label for="password">From:</label>
                            @Html.TextBoxFor(o=>o.LeaveFrom, new { @class="form-control",@id="datepickerLeaveFrom",@readonly="readonly" , @required = "required" })
                            @Html.ValidationMessageFor(o=>o.LeaveFrom,"", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label for="password">To:</label>
                            @Html.TextBoxFor(o=>o.LeaveTo, new { @class="form-control",@id="datepickerLeaveTo", @readonly="readonly", @required = "required" })
                            @Html.ValidationMessageFor(o=>o.LeaveTo,"", new { @class = "text-danger" })
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>            <a href="@Url.Action("Index","Pers")" class="btn btn-primary">Back</a>

                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{

    <script>
        $("#datepickerLeaveFrom").datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true
        });

        $("#datepickerLeaveFrom").on("change", function () {
            const startDate = new Date($("#datepickerLeaveFrom").val());
            console.log(startDate)
            $("#datepickerLeaveTo").datepicker({
                minDate: startDate,
                format: 'yyyy-mm-dd',
                autoclose: true
            });
        });




    </script>
}

IFMApps/Views/Pers/Patrol.cshtml
@using System.Data

@model DataSet
@{
    ViewData["Title"] = "Patrol Page";

}
<div class="container removemargincontainer">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 widthdesktop">

            <div class="card">
                <div class="card-body removemargin">
                    <button class="btn btn-sm btn-primary" onclick="scanPatrolPoint()"><b>SCAN</b></button>

                    <a href="@Url.Action("ReportIncident","Pers")" class="btn btn-sm btn-primary"><b>Report Incident</b></a>
                    <a href="@Url.Action("Index","Pers")" class="btn btn-sm btn-primary"><b>Back</b></a>


                    <hr />
                    @{
                        foreach (DataTable table in Model.Tables)
                        {
                            if (table.Columns.Contains("Label"))
                            {
                                @foreach (DataColumn col in table.Columns)
                                {
                                    if (col.ColumnName != "Msg")
                                    {
                                        foreach (DataRow row in table.Rows)
                                        {
                                            <p class="text-center"><b>@row[col]</b></p>
                                        }
                                    }

                                }
                            }
                            else if (table.TableName == "DT1")
                            {
                                <div style="height:200px" class="table-responsive overflow-auto">

                                    <table class="table table-bordered">
                                        <thead>
                                            <tr style="page-break-inside:avoid">
                                                @foreach (DataColumn col in table.Columns)
                                                {
                                                    if (col.ColumnName.ToLower() == "time" || col.ColumnName.ToLower() == "name")
                                                    {
                                                        <th style="text-align:left">@col.ColumnName</th>
                                                    }
                                                }
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (DataRow row in table.Rows)
                                            {
                                                <tr style="page-break-inside:avoid">
                                                    @foreach (DataColumn col in table.Columns)
                                                    {
                                                        if (col.ColumnName.ToLower() == "time" || col.ColumnName.ToLower() == "name")
                                                        {
                                                            <td>@row[col]</td>
                                                        }
                                                    }
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>

                            }
                        }
                    }

                </div>
            </div>
        </div>
    </div>
</div>

<!-- The modal -->
<div class="modal fade" id="modalCameraQR">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title text-center"><b>Scan QR Or Tap NFC</b></h4>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div style="width:100%" id="reader"></div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-info" onclick="closeScanner()">Close</button>
            </div>

        </div>
    </div>
</div>

@Html.Hidden("Latitude")
@Html.Hidden("Longitude")
@section Scripts{
    <script src="~/js/openstreetmap.js"></script>
    <script src="~/js/qrscanner.js"></script>
    <script src="~/js/getlocation.js"></script>
    <script type="text/javascript">

        var bluetoothDevice;

        function scanPatrolPoint() {

            $("#modalCameraQR").modal("show");
            html5QrCode.start({ facingMode: "environment" }, config, onScanSuccessPatrol);
            removeScanWithFile();
            GetLocation();
            scanNFCPatrolPoint();
        }

        function scanNFCPatrolPoint() {

            if ("NDEFReader" in window) {
                try {
                    const abortController = new AbortController();
                    const ndef = new NDEFReader();
                    ndef.scan({ signal: abortController.signal });

                    ndef.addEventListener("readingerror", () => {
                        SwalAlert("Scan Patrol", "Cannot read data from the NFC tag. Try another one?", "error")
                    });

                    ndef.addEventListener("reading", ({ message, serialNumber }) => {
                        console.log(serialNumber);
                        $.ajax({
                            url: '@Url.Action("ScanPatrol", "Pers")',
                            type: 'POST',
                            data: { QROrNFC: serialNumber, lng: $("#Longitude").val(), lat: $("#Latitude").val(), DateTime: GetDateTimeFormat() },
                            dataType: "JSON",
                            success: function (data) {
                                abortController.abort();
                                console.log(data);
                                if (data.msg == "OK") {
                                    SwalAlertLocationReload(data.msg, data.msg2, 'success');
                                }
                                else {
                                    SwalAlertLocationReload(data.msg, data.msg2, 'error');
                                }

                                setInterval(function () {
                                    location.reload();
                                }, 5000);
                            }
                        });

                    });
                } catch (error) {
                    SwalAlert("Scan NFC", "error : " + error, "error")
                }
            } else {
                SwalAlert("Scan Patrol", "your devices / browser not supported NFC scanning , you can do Scan QR for patrol or use supported NFC devices for scan NFC", "info")
            }
        }

        function closeScanner() {
            html5QrCode.stop();
            $("#modalCameraQR").modal("hide");
        }
        function onScanSuccessPatrol(qrCodeMessage) {

            console.log(`QR matched = ${qrCodeMessage}`);
            console.log($("#Longitude").val())
            console.log($("#Latitude").val())

            html5QrCode.stop();

            $.ajax({
                url: '@Url.Action("ScanPatrol", "Pers")',
                type: 'POST',
                data: { QROrNFC: `${qrCodeMessage}`, lng: $("#Longitude").val(), lat: $("#Latitude").val(), DateTime: GetDateTimeFormat() },
                dataType: "JSON",
                success: function (data) {
                    console.log(data);
                    if (data.msg == "OK") {
                        SwalAlertLocationReload(data.msg, data.msg2, 'success');
                        setInterval(function () {
                            location.reload();
                        }, 5000);
                        return true;
                    }
                    else {
                        SwalAlertLocationReload(data.msg, data.msg2, 'error');
                        setInterval(function () {
                            location.reload();
                        }, 5000);
                        return false;
                    }
                }
            });




            //$.ajax({
            //    url: '@Url.Action("GetNextPoint", "Pers")',
            //    type: 'POST',
            //    dataType: "JSON",
            //    success: function (data) {
            //        var dataPointJson = JSON.parse(data);
            //        console.log(dataPointJson);
            //        if (dataPointJson.DT1.length > 0) {
            //            dataPointJson.DT1.forEach(function (item) {
            //                if (item.QR == `${qrCodeMessage}`) {
            //                    console.log(item);

            //                } else {
            //                    console.log(item.QR)
            //                    console.log(qrCodeMessage)
            //                }
            //            });
            //            SwalAlertLocationReload("Scan Patrol", "The QR code you scanned does not match your current patrol route.", 'error');
            //            setInterval(function () {
            //                location.reload();
            //            }, 5000);
            //            return false;
            //        } else {
            //            swal({
            //                title: "Quiet Protect",
            //                text: "End Of Patrol Point",
            //                icon: "info"
            //            }).then((value) => {
            //                window.location.href = "/IFMApp/Pers/Index";
            //            });;
            //            return true;

            //        }
            //    }
            //});





        }


    </script>
}

IFMApps/Views/Pers/PersAvail.cshtml
@using System.Data

@model DataSet
@{
    ViewData["Title"] = "Available Pers";

}
<div class="container removemargincontainer">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 widthdesktop">
            <a href="@Url.Action("Index","Pers")" class="btn btn-primary"><b>Back</b></a>

            <hr />
            @{
                if (Model.Tables.Count > 0)
                {
                    foreach (DataTable table in Model.Tables)
                    {
                        if (table.Columns.Contains("Msg"))
                        {
                            @foreach (DataColumn col in table.Columns)
                            {
                                foreach (DataRow row in table.Rows)
                                {
                                    <p class="text-center"><b>@row[col]</b></p>
                                }
                            }
                        }
                        else
                        {
                            <div style="height:500px" class="table-responsive overflow-auto">

                                <table class="table table-bordered">
                                    <thead>
                                        <tr style="page-break-inside:avoid">
                                            <td></td>
                                            @foreach (DataColumn col in table.Columns)
                                            {
                                                if (col.ColumnName != "idattend")
                                                {
                                                    <th style="text-align:left">@col.ColumnName</th>

                                                }
                                            }
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (DataRow row in table.Rows)
                                        {
                                            <tr style="page-break-inside:avoid">
                                                <td><a href="@Url.Action("TakeAttend","Pers", new { idAttend = @row["idattend"]})">Take</a></td>
                                                @foreach (DataColumn col in table.Columns)
                                                {

                                                    if (col.ColumnName != "idattend")
                                                    {
                                                        <td>@row[col]</td>

                                                    }
                                                }
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                        }
                    }

                }
                else
                {
                    <h5>No Slot Available !</h5>
                }
            }

        </div>
    </div>
</div>

IFMApps/Views/Pers/QRScanner.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container removemargincontainer">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 widthdesktop">
            <div class="card">
                <div class="card-header">
                    <h4>Scan QR Test</h4>
                </div>
                <div class="card-body removemargin">
                    <div style="width:100%" id="reader"></div>
                    <hr />
                    <div class="text-center">
                        <a href="@Url.Action("Login","Account")" class="btn btn-success">Close</a>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

@Html.Hidden("Latitude")
@Html.Hidden("Longitude")
@section Scripts{
    <script src="~/js/openstreetmap.js"></script>
    <script src="~/js/qrscanner.js"></script>
    <script src="~/js/getlocation.js"></script>
    <script type="text/javascript">
        startScanner()
        function startScanner() {

            html5QrCode.start({ facingMode: "environment" }, config, onScanSuccessPatrol);
            removeScanWithFile();
            GetLocation();
        }

        function stopScanner() {
            html5QrCode.stop();
        }
        function onScanSuccessPatrol(qrCodeMessage) {

            console.log(`QR matched = ${qrCodeMessage}`);
            console.log($("#Longitude").val())
            console.log($("#Latitude").val())

            html5QrCode.stop();

            $.ajax({
                url: '@Url.Action("QRScanner", "Pers")',
                type: 'POST',
                data: { qR: `${qrCodeMessage}`, lng: $("#Longitude").val(), lat: $("#Latitude").val() },
                dataType: "JSON",
                success: function (data) {
                    console.log(data);
                    SwalAlertLocationReload(data.msg, data.msg2, 'info');

                }
            });
        }




    </script>
}

IFMApps/Views/Pers/ReportIncident.cshtml
@model IFMApps.Helpers.ReportIncidentParam
@{
    ViewData["Title"] = "Report Fault";
}

<div class="container removemargincontainer">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 widthdesktop">
            <div class="card">
                <div class="card-header">
                    <h4>Report Incident</h4>
                </div>
                <div class="card-body removemargin">
                    @using (Html.BeginForm("SubmitIncident", "Pers", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {

                        <div class="form-group">
                            <div class="attachment-input">
                                <button type="button" class="btn btn-secondary" style="cursor:pointer">Browse for video</button>
                                <span class="attachment-file-name">No file chosen</span>
                                <input type="file" name="File" id="inputAttachment">

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Description">Description:</label>
                            @Html.TextAreaFor(o=>o.Description, new { @class="form-control" })
                            @Html.ValidationMessageFor(o=>o.Description,"", new { @class = "text-danger" })
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="@Url.Action("Patrol","Pers")" class="btn btn-primary">Back</a>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
    </script>
}